controllers/login_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify
from flask_login import login_user, login_required, logout_user
from controllers.utils.utils import login_manager, login_existe, SessionLocal
from models.models import Master, Usuario
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import scoped_session

login_bp = Blueprint('login_bp', __name__, template_folder='templates')

# Cria sessão segura com escopo de thread (boa prática com Flask)
db_session = scoped_session(SessionLocal)


@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    elif request.method == 'POST':
        login_input = request.form['login']
        senha_input = request.form['senha']

        db = SessionLocal()
        try:
            # Verifica Master
            master = db.query(Master).filter_by(login=login_input).first()
            if master and check_password_hash(master.senha, senha_input):
                login_user(master)
                session['tipo_usuario'] = 'master'
                return redirect(url_for('master_bp.master'))

            # Verifica Usuario
            usuario = db.query(Usuario).filter_by(login=login_input).first()
            if usuario and check_password_hash(usuario.senha, senha_input):
                login_user(usuario)
                session['tipo_usuario'] = 'usuario'
                return redirect(url_for('usuario_bp.usuario'))

        finally:
            db.close()

        erro = "Login ou senha inválidos"
        return render_template('login.html', erro=erro)


@login_manager.user_loader
def user_loader(user_id):
    tipo = session.get('tipo_usuario')
    db = SessionLocal()
    try:
        if tipo == 'master':
            return db.get(Master, int(user_id))
        elif tipo == 'usuario':
            return db.get(Usuario, int(user_id))
        # elif tipo == 'cliente':
        #     return db.get(Cliente, int(user_id))
    finally:
        db.close()
    return None


@login_bp.route('/verificar_login', methods=['POST'])
def verificar_login():
    login = request.json.get('login')
    if not login:
        return jsonify({'disponivel': False, 'mensagem': 'Login inválido.'})

    if login_existe(login):
        return jsonify({'disponivel': False, 'mensagem': 'Login já está em uso.'})
    else:
        return jsonify({'disponivel': True, 'mensagem': 'Login disponível!'})


@login_bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    session.clear()  # Limpa tipo de usuário e demais dados da sessão
    return redirect(url_for('login_bp.login'))

controllers/master_controller.py
from flask import render_template, request, redirect, url_for, session, abort, send_file
from flask_login import login_user, login_required
from models.models import Master, Usuario
from controllers.utils.utils import tipo_usuario_requerido, login_existe, cadastrar_usuario, cadastrar_cliente, cadastrar_animal, cadastrar_tipo_servico, renderizar_lista_usuarios, gerar_relatorio, renderizar_lista_clientes
from flask import Blueprint
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from models.models import *


# Criando a sessão para interagir com o banco de dados
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


master_bp = Blueprint('master_bp', __name__)


# Cadastro do Master (Se for só um master, só se faz isso uma vez)
@master_bp.route('/cadastro/master', methods = ['GET','POST'])
#@tipo_usuario_requerido('master') # PARA CADASTRAR MASTER TEM QUE REMOVER ESSA LINHA
def cadastrarmaster():
    if request.method == 'GET':
        return render_template('/cadastroMaster.html')
    elif request.method =='POST':
        nome = request.form['masterNome']
        login = request.form['masterLogin']
        senha = request.form['masterSenha']
        senha_hash = generate_password_hash(senha)  # senha é o valor vindo do form
        
        if login_existe(login):
            return render_template('/cadastroMaster.html', erro="Esse login já está em uso. Escolha outro.")


        master = Master(nome=nome, login=login, senha=senha_hash)
        with SessionLocal() as db:
            db.add(master)
            db.commit()
            # Recarrega o master da base de dados para garantir que esteja na sessão
            master = db.query(Master).filter_by(login=login).first()

            session['tipo_usuario'] = 'master'
            login_user(master)

        return redirect(url_for('master_bp.master'))

@master_bp.route('/master/cadastro/usuario', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_usuario():
    return cadastrar_usuario('master')

@master_bp.route('/master/cadastro/cliente', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_cliente():
    return cadastrar_cliente('master')

@master_bp.route('/master/cadastro/animal', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_animal():
    return cadastrar_animal('master')

@master_bp.route('/master/cadastro/tipo-servico', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_tipo_servico():
    return cadastrar_tipo_servico('master')

@master_bp.route('/master/home')
@login_required
@tipo_usuario_requerido('master')
def master():
    return render_template('master/homeMaster.html')

@master_bp.route('/master/cadastro')
@login_required
@tipo_usuario_requerido('master')
def cadastros_realizados():
    return render_template('master/homeCadastrosRealizados.html')


@master_bp.route('/master/cadastro/usuario/list')
@login_required
@tipo_usuario_requerido('master')
def listar_usuarios():
    return renderizar_lista_usuarios()

@master_bp.route('/master/cadastro/cliente/list')
@login_required
@tipo_usuario_requerido('master')
def listar_master_clientes():
    return renderizar_lista_clientes()

@master_bp.route('/master/usuarios/editar/<tipo>/<int:id>', methods=['POST'])
@login_required
@tipo_usuario_requerido('master')
def editar_usuario(tipo,id):
    with SessionLocal() as db:
        if tipo == 'usuario':
            usuario = db.get(Usuario, id)
            if not usuario:
                abort(404)

            usuario.nome = request.form['nome']
            usuario.email = request.form['email']
            usuario.telefone = request.form['telefone']
            db.commit()
        elif tipo == 'cliente':
            cliente = db.get(Cliente, id)
            if not cliente:
                abort(404)

            cliente.nome = request.form['nome']
            cliente.email = request.form['email']
            cliente.telefone = request.form['telefone']
            db.commit()
    return redirect(url_for('master_bp.listar_usuarios'))

@master_bp.route('/master/usuarios/excluir/<int:id>', methods=['POST'])
@login_required
@tipo_usuario_requerido('master')
def excluir_usuario(id):
    with SessionLocal() as db:
        usuario = db.get(Usuario, id)
        if not usuario:
            abort(404)

        db.delete(usuario)
        db.commit()

    return redirect(url_for('master_bp.listar_usuarios'))


@master_bp.route('/master/cadastro/<tipo>/list/relatorio/pdf') #O tipo vem do template listar_usuarios.html
@login_required
@tipo_usuario_requerido('master')
def relatorio_pdf(tipo):
    pdf_file, nome_arquivo = gerar_relatorio(tipo)
    if not pdf_file:
        return "Erro ao gerar PDF", 400
    return send_file(pdf_file, download_name=nome_arquivo, as_attachment=False)

controllers/usuario_controller.py
from flask import render_template, send_file
from flask_login import login_required
from models.models import *
# from .login_controller import *
from controllers.utils.utils import tipo_usuario_requerido, cadastrar_cliente, cadastrar_animal, cadastrar_tipo_servico, gerar_relatorio, renderizar_lista_clientes
from flask import Blueprint


# Criando a sessão para interagir com o banco de dados
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

usuario_bp = Blueprint('usuario_bp', __name__, url_prefix='/usuario')


@usuario_bp.route('/home')
@login_required
@tipo_usuario_requerido('usuario')
def usuario():
    return render_template('usuario/homeUsuario.html')

@usuario_bp.route('/cadastro')
@login_required
@tipo_usuario_requerido('usuario')
def cadastros_realizados():
    return render_template('usuario/homeCadastrosRealizados.html')

@usuario_bp.route('/cadastro/cliente/list')
@login_required
@tipo_usuario_requerido('usuario')
def listar_usuario_clientes():
    return renderizar_lista_clientes()


@usuario_bp.route('/cadastro/cliente', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_cliente():
    return cadastrar_cliente('usuario')


@usuario_bp.route('/cadastro/animal', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_animal():
    return cadastrar_animal('usuario')

@usuario_bp.route('/cadastro/tipo-servico', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_tipo_servico():
    return cadastrar_tipo_servico('usuario')


@usuario_bp.route('/<tipo>/list/relatorio/pdf') #O tipo vem do template listar_usuarios.html
@login_required
@tipo_usuario_requerido('usuario')
def relatorio_pdf(tipo):
    pdf_file, nome_arquivo = gerar_relatorio(tipo)
    if not pdf_file:
        return "Erro ao gerar PDF", 400
    return send_file(pdf_file, download_name=nome_arquivo, as_attachment=False)

templates/usuario/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style> @import url('https://fonts.googleapis.com/css2?family=Winky+Sans:ital,wght@0,300..900;1,300..900&display=swap');</style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
        
</head>
<body>
    <div class="container mt-5">
        <h2>Cadastro de Usuário</h2>
        <form action="/usuario/cadastro_usuario" method="POST">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" id="nome" name="nome" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="login">Login</label>
                <input type="text" id="login" name="login" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="senha">Senha</label>
                <input type="password" id="senha" name="senha" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="telefone">Telefone</label>
                <input type="text" id="telefone" name="telefone" class="form-control" required>
            </div>

            <button type="submit" class="btn btn-primary btn-lg">Cadastrar</button>
        </form>
    </div>
    <!-- Importando o Bootstrap JS para a funcionalidade do formulário -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    
</body>
</html>

templates/usuario/cadastroUsuario.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Winky+Sans:ital,wght@0,300..900;1,300..900&display=swap');
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="icon" href="../../static/images/animais-de-estimacao.png" type="image/png">
    <!-- Importando o Bootstrap JS para a funcionalidade do formulário 
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->



    <title>Cadastro de Usuário</title>
</head>



<body>
    <header class="fixed-top" id="Header">
        <div id="container2">
            <!-- Menu suspenso -->
            <div class="dropdown" id="menuDropdown"  tabindex="0" role="button" aria-haspopup="true" aria-expanded="false">
                <div class="text-white" id="menuToggle" role="button">
                    <i class="bi bi-list"></i>
                </div>
                <ul class="dropdown-menu" id="menuItems">
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.usuario') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.master') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-house me-3"></i>Início
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastros_realizados') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastros_realizados') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-user me-3"></i>Acessar cadastros realizados
                        </a>
                    </li>
                    {% if session['tipo_usuario'] == 'master' %}
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{{ url_for('master_bp.cadastro_usuario') }}">
                                <i class="fa-solid fa-user me-3"></i>Cadastro de usuários
                            </a>
                        </li>
                    {% endif %} 
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_cliente') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_cliente') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-users me-3"></i>Cadastro de clientes
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_animal') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_animal') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-dog me-3"></i>Cadastro de animais
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-user-md me-3"></i>Cadastro de veterinários
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="#">
                            <i class="fa-solid fa-file-medical me-3"></i>Cadastro de prontuário
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-briefcase-medical me-3"></i>Cadastro de serviços
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_tipo_servico') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_tipo_servico') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-paw me-3"></i>Cadastro de tipo de serviço
                        </a>
                    </li>
                </ul>
            </div>

            <div class="titulo">PetShop</div>
            <div><img class="imgPetHouse" src="../../static/images/pet-house.png" alt="image"></div>

        </div>



        <div class="usuarioSessao">
            Login da sessão: ({{current_user.login}}) <a href="#" class="sair"
                onclick="document.getElementById('logout-form').submit();" data-bs-toggle="tooltip"
                title="Logout da sessão">Sair</a>

            <form id="logout-form" action="{{ url_for('login_bp.logout') }}" method="POST" style="display: none;">
                <!-- Você pode adicionar um CSRF token aqui se estiver usando Flask-WTF -->
            </form>

            <br>
            <div class="theme-toggle">
                <label class="switch" data-bs-toggle="tooltip" title="Alternar tema claro/escuro">
                    <input type="checkbox" id="toggleTheme">
                    <span class="slider round"></span>
                </label>
                <i id="themeIcon" class="fas fa-sun theme-icon"></i> <!-- Ícone inicial -->
            </div>
        </div>

    </header>

    <main class="container paddingBottom50px">

        <h2>Cadastro de Usuários</h2>
        <div class="container-box">

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <form action="" method="POST">


                <div class="form-group ">
                    <label for="nome">Nome</label>
                    <input type="text" id="nome" name="usuarioNome" class="form-control" required placeholder="Nome">
                </div>

                <div class="row">
                <div class="form-group col-md-6">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="usuarioEmail" class="form-control" required
                        placeholder="Email">
                </div>
                <div class="form-group col-md-6">
                    <label for="telefone">Telefone</label>
                    <input type="text" id="telefone" name="usuarioTelefone" class="form-control" required
                        placeholder="(00) 00000-0000">
                </div>
                </div>

                <div class="form-group">
                    <label for="login">Login</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        <input type="text" class="form-control" id="login" name="usuarioLogin" required
                            placeholder="Login">
                    </div>

                </div>

                <div id="login-feedback" class="form-text"></div>
                
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password" id="senha" name="usuarioSenha" class="form-control" required
                        placeholder="Senha">
                </div>
                


                <div id="divButtonCadastrar" style="padding-top: 20px;">

                    <button type="submit" class="btn btn-primary btn-lg">Cadastrar</button>
                </div>

            </form>
        </div>

        <div class="footer">
            &copy; 2025. Todos os direitos reservados.
        </div>

    </main>


    <script src="../../static/main.js"></script>
</body>

</html>

templates/usuario/homeCadastrosRealizados.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="../static/images/animais-de-estimacao.png" type="image/png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Winky+Sans:ital,wght@0,300..900;1,300..900&display=swap');
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <link rel="stylesheet" href="../static/styles.css">
    <title>Home</title>
</head>



<body>
    <header class="fixed-top" id="Header">
        <div id="container2">

            <!-- Menu suspenso -->
            <div class="dropdown" id="menuDropdown" tabindex="0" role="button" aria-haspopup="true"
                aria-expanded="false">
                <div class="text-white" id="menuToggle" role="button">
                    <i class="bi bi-list"></i>
                </div>
                <ul class="dropdown-menu" id="menuItems">
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.usuario') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.master') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-house me-3"></i>Início
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastros_realizados') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastros_realizados') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-user me-3"></i>Acessar cadastros realizados
                        </a>
                    </li>                    
                    {% if session['tipo_usuario'] == 'master' %}
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="{{ url_for('master_bp.cadastro_usuario') }}">
                            <i class="fa-solid fa-user me-3"></i>Cadastro de usuários
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_cliente') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_cliente') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-users me-3"></i>Cadastro de clientes
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_animal') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_animal') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-dog me-3"></i>Cadastro de animais
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-user-md me-3"></i>Cadastro de veterinários
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-file-medical me-3"></i>Cadastro de prontuário
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-briefcase-medical me-3"></i>Cadastro de serviços
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_tipo_servico') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_tipo_servico') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-paw me-3"></i>Cadastro de tipo de serviço
                        </a>
                    </li>
                </ul>
            </div>

            <div class="titulo">PetShop</div>
            <div><img class="imgPetHouse" src="../../static/images/pet-house.png" alt="image"></div>
        </div>
        <div class="usuarioSessao">

            Login da sessão: ({{current_user.login}}) <a href="#" class="sair"
                onclick="document.getElementById('logout-form').submit();" data-bs-toggle="tooltip"
                title="Logout da sessão">Sair</a>

            <form id="logout-form" action="{{ url_for('login_bp.logout') }}" method="POST" style="display: none;">
                <!-- Você pode adicionar um CSRF token aqui se estiver usando Flask-WTF -->
            </form>

            <br>
            <div class="theme-toggle">
                <label class="switch" data-bs-toggle="tooltip" title="Alternar tema claro/escuro">
                    <input type="checkbox" id="toggleTheme">
                    <span class="slider round"></span>
                </label>
                <i id="themeIcon" class="fas fa-moon theme-icon"></i> <!-- Ícone inicial -->
            </div>

        </div>
    </header>
    <main class="container">
        <h2>Cadastros realizados</h2>
        <div class="container-box text-center" id="opcoes">
            <div class="row g-3">


                <div class="col-md-6 mx-auto">
                    <a href="{{ url_for('usuario_bp.listar_usuario_clientes') }}">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-users"></i>Clientes cadastrados</button>
                    </a>
                </div>

                <div class="col-md-6 mx-auto">
                    <a href="{{ url_for('usuario_bp.cadastro_animal') }}">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-dog"></i>Animais
                            cadastrados</button>
                    </a>
                </div>

                <div class="col-md-6 mx-auto">
                    <a href="#">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-user-md"></i>Veterinários
                            cadastrados</button>
                    </a>
                </div>

                <div class="col-md-6 mx-auto">
                    <a href="#">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-file-medical"></i>Prontuários
                            cadastrados</button>
                    </a>
                </div>

                <div class="col-md-6 mx-auto">
                    <a href="#">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-briefcase-medical"></i>Serviços
                            cadastrados</button>
                    </a>
                </div>

                <div class="col-md-6 mx-auto">
                    <a href="{{ url_for('usuario_bp.cadastro_tipo_servico') }}">
                        <button class="btn btn-primary btn-custom"><i class="fas fa-paw"></i>Tipo de Serviço cadastrados</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="footer">
            &copy; 2025. Todos os direitos reservados.
        </div>

    </main>

    <script src="../../static/main.js"></script>
</body>

</html>