controllers/login_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify
from flask_login import login_user, login_required, logout_user
from controllers.utils.utils import login_manager, login_existe, SessionLocal
from models.models import Master, Usuario
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import scoped_session

login_bp = Blueprint('login_bp', __name__, template_folder='templates')

# Cria sessão segura com escopo de thread (boa prática com Flask)
db_session = scoped_session(SessionLocal)


@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    elif request.method == 'POST':
        login_input = request.form['login']
        senha_input = request.form['senha']

        db = SessionLocal()
        try:
            # Verifica Master
            master = db.query(Master).filter_by(login=login_input).first()
            if master and check_password_hash(master.senha, senha_input):
                login_user(master)
                session['tipo_usuario'] = 'master'
                return redirect(url_for('master_bp.master'))

            # Verifica Usuario
            usuario = db.query(Usuario).filter_by(login=login_input).first()
            if usuario and check_password_hash(usuario.senha, senha_input):
                login_user(usuario)
                session['tipo_usuario'] = 'usuario'
                return redirect(url_for('usuario_bp.usuario'))

        finally:
            db.close()

        erro = "Login ou senha inválidos"
        return render_template('login.html', erro=erro)


@login_manager.user_loader
def user_loader(user_id):
    tipo = session.get('tipo_usuario')
    db = SessionLocal()
    try:
        if tipo == 'master':
            return db.get(Master, int(user_id))
        elif tipo == 'usuario':
            return db.get(Usuario, int(user_id))
        # elif tipo == 'cliente':
        #     return db.get(Cliente, int(user_id))
    finally:
        db.close()
    return None


@login_bp.route('/verificar_login', methods=['POST'])
def verificar_login():
    login = request.json.get('login')
    if not login:
        return jsonify({'disponivel': False, 'mensagem': 'Login inválido.'})

    if login_existe(login):
        return jsonify({'disponivel': False, 'mensagem': 'Login já está em uso.'})
    else:
        return jsonify({'disponivel': True, 'mensagem': 'Login disponível!'})


@login_bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    session.clear()  # Limpa tipo de usuário e demais dados da sessão
    return redirect(url_for('login_bp.login'))

controllers/master_controller.py
from flask import render_template, request, redirect, url_for, session, abort, send_file
from flask_login import login_user, login_required
from models.models import Master, Usuario
from controllers.utils.utils import tipo_usuario_requerido, login_existe, cadastrar_usuario, cadastrar_cliente, cadastrar_animal, cadastrar_tipo_servico, renderizar_lista_usuarios, gerar_relatorio, renderizar_lista_clientes
from flask import Blueprint
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from models.models import *


# Criando a sessão para interagir com o banco de dados
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


master_bp = Blueprint('master_bp', __name__)


# Cadastro do Master (Se for só um master, só se faz isso uma vez)
@master_bp.route('/cadastro/master', methods = ['GET','POST'])
#@tipo_usuario_requerido('master') # PARA CADASTRAR MASTER TEM QUE REMOVER ESSA LINHA
def cadastrarmaster():
    if request.method == 'GET':
        return render_template('/cadastroMaster.html')
    elif request.method =='POST':
        nome = request.form['masterNome']
        login = request.form['masterLogin']
        senha = request.form['masterSenha']
        senha_hash = generate_password_hash(senha)  # senha é o valor vindo do form
        
        if login_existe(login):
            return render_template('/cadastroMaster.html', erro="Esse login já está em uso. Escolha outro.")


        master = Master(nome=nome, login=login, senha=senha_hash)
        with SessionLocal() as db:
            db.add(master)
            db.commit()
            # Recarrega o master da base de dados para garantir que esteja na sessão
            master = db.query(Master).filter_by(login=login).first()

            session['tipo_usuario'] = 'master'
            login_user(master)

        return redirect(url_for('master_bp.master'))

@master_bp.route('/master/cadastro/usuario', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_usuario():
    return cadastrar_usuario('master')

@master_bp.route('/master/cadastro/cliente', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_cliente():
    return cadastrar_cliente('master')

@master_bp.route('/master/cadastro/animal', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_animal():
    return cadastrar_animal('master')

@master_bp.route('/master/cadastro/tipo-servico', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('master')
def cadastro_tipo_servico():
    return cadastrar_tipo_servico('master')

@master_bp.route('/master/home')
@login_required
@tipo_usuario_requerido('master')
def master():
    return render_template('master/homeMaster.html')

@master_bp.route('/master/cadastro')
@login_required
@tipo_usuario_requerido('master')
def cadastros_realizados():
    return render_template('master/homeCadastrosRealizados.html')


@master_bp.route('/master/cadastro/usuario/list')
@login_required
@tipo_usuario_requerido('master')
def listar_usuarios():
    return renderizar_lista_usuarios()

@master_bp.route('/master/cadastro/cliente/list')
@login_required
@tipo_usuario_requerido('master')
def listar_master_clientes():
    return renderizar_lista_clientes()

@master_bp.route('/master/usuarios/editar/<tipo>/<int:id>', methods=['POST'])
@login_required
@tipo_usuario_requerido('master')
def editar_usuario(tipo,id):
    with SessionLocal() as db:
        if tipo == 'usuario':
            usuario = db.get(Usuario, id)
            if not usuario:
                abort(404)

            usuario.nome = request.form['nome']
            usuario.email = request.form['email']
            usuario.telefone = request.form['telefone']
            db.commit()
        elif tipo == 'cliente':
            cliente = db.get(Cliente, id)
            if not cliente:
                abort(404)

            cliente.nome = request.form['nome']
            cliente.email = request.form['email']
            cliente.telefone = request.form['telefone']
            db.commit()
    return redirect(url_for('master_bp.listar_usuarios'))

@master_bp.route('/master/usuarios/excluir/<int:id>', methods=['POST'])
@login_required
@tipo_usuario_requerido('master')
def excluir_usuario(id):
    with SessionLocal() as db:
        usuario = db.get(Usuario, id)
        if not usuario:
            abort(404)

        db.delete(usuario)
        db.commit()

    return redirect(url_for('master_bp.listar_usuarios'))


@master_bp.route('/master/cadastro/<tipo>/list/relatorio/pdf') #O tipo vem do template listar_usuarios.html
@login_required
@tipo_usuario_requerido('master')
def relatorio_pdf(tipo):
    pdf_file, nome_arquivo = gerar_relatorio(tipo)
    if not pdf_file:
        return "Erro ao gerar PDF", 400
    return send_file(pdf_file, download_name=nome_arquivo, as_attachment=False)

controllers/usuario_controller.py
from flask import render_template, send_file
from flask_login import login_required
from models.models import *
# from .login_controller import *
from controllers.utils.utils import tipo_usuario_requerido, cadastrar_cliente, cadastrar_animal, cadastrar_tipo_servico, gerar_relatorio, renderizar_lista_clientes
from flask import Blueprint


# Criando a sessão para interagir com o banco de dados
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

usuario_bp = Blueprint('usuario_bp', __name__, url_prefix='/usuario')


@usuario_bp.route('/home')
@login_required
@tipo_usuario_requerido('usuario')
def usuario():
    return render_template('usuario/homeUsuario.html')

@usuario_bp.route('/cadastro')
@login_required
@tipo_usuario_requerido('usuario')
def cadastros_realizados():
    return render_template('usuario/homeCadastrosRealizados.html')

@usuario_bp.route('/cadastro/cliente/list')
@login_required
@tipo_usuario_requerido('usuario')
def listar_usuario_clientes():
    return renderizar_lista_clientes()


@usuario_bp.route('/cadastro/cliente', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_cliente():
    return cadastrar_cliente('usuario')


@usuario_bp.route('/cadastro/animal', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_animal():
    return cadastrar_animal('usuario')

@usuario_bp.route('/cadastro/tipo-servico', methods=['GET', 'POST'])
@login_required
@tipo_usuario_requerido('usuario')
def cadastro_tipo_servico():
    return cadastrar_tipo_servico('usuario')


@usuario_bp.route('/<tipo>/list/relatorio/pdf') #O tipo vem do template listar_usuarios.html
@login_required
@tipo_usuario_requerido('usuario')
def relatorio_pdf(tipo):
    pdf_file, nome_arquivo = gerar_relatorio(tipo)
    if not pdf_file:
        return "Erro ao gerar PDF", 400
    return send_file(pdf_file, download_name=nome_arquivo, as_attachment=False)

templates/cliente/listar_clientes.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="icon" href="{{ url_for('static', filename='/images/animais-de-estimacao.png') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Winky+Sans:ital,wght@0,300..900;1,300..900&display=swap');
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='/styles.css') }}">


    <title>Lista de clientes</title>
</head>



<body>
    <header class="fixed-top" id="Header">
        <div id="container2">

            <!-- Menu suspenso -->
            <div class="dropdown" id="menuDropdown" tabindex="0" role="button" aria-haspopup="true"
                aria-expanded="false">
                <div class="text-white" id="menuToggle" role="button">
                    <i class="bi bi-list"></i>
                </div>
                <ul class="dropdown-menu" id="menuItems">
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.usuario') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.master') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-house me-3"></i>Início
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastros_realizados') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastros_realizados') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-user me-3"></i>Acessar cadastros realizados
                        </a>
                    </li>
                    {% if session['tipo_usuario'] == 'master' %}
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                            href="{{ url_for('master_bp.cadastro_usuario') }}">
                            <i class="fa-solid fa-user me-3"></i>Cadastro de usuários
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_cliente') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_cliente') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-users me-3"></i>Cadastro de clientes
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_animal') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_animal') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-dog me-3"></i>Cadastro de animais
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-user-md me-3"></i>Cadastro de veterinários
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-file-medical me-3"></i>Cadastro de prontuário
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="fa-solid fa-briefcase-medical me-3"></i>Cadastro de serviços
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.cadastro_tipo_servico') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.cadastro_tipo_servico') }}
                    {% else %}
                        #
                    {% endif %}">
                            <i class="fa-solid fa-paw me-3"></i>Cadastro de tipo de serviço
                        </a>
                    </li>
                </ul>
            </div>

            <div class="titulo">PetShop</div>
            <div><img class="imgPetHouse" src="{{ url_for('static', filename='images/pet-house.png') }}" alt="image"></div>
            
        </div>

        <div class="usuarioSessao">
            <div>
                Login da sessão: ({{current_user.login}}) <a href="#" class="sair"
                    onclick="document.getElementById('logout-form').submit();" data-bs-toggle="tooltip"
                    title="Logout da sessão">Sair</a>

                <form id="logout-form" action="{{ url_for('login_bp.logout') }}" method="POST" style="display: none;">
                    <!-- Você pode adicionar um CSRF token aqui se estiver usando Flask-WTF -->
                </form>
            </div>

            <div class="theme-toggle">
                <label class="switch" data-bs-toggle="tooltip" title="Alternar tema claro/escuro">
                    <input type="checkbox" id="toggleTheme">
                    <span class="slider round"></span>
                </label>
                <i id="themeIcon" class="fas fa-sun theme-icon"></i> <!-- Ícone inicial -->
            </div>

        </div>
    </header>
    <main class="container paddingBottom50px">
        <h2>Lista de clientes cadastrados</h2>

        <div class="row mb-3">
            <div class="col-md-9 col-12 mb-2 mb-md-0">
                <input type="text" class="form-control w-50" id="pesquisaUsuarios" placeholder="Pesquisar clientes...">
            </div>
            <div class="col-md-3 col-12">
                <a href="{% if session['tipo_usuario'] == 'usuario' %}
                        {{ url_for('usuario_bp.relatorio_pdf', tipo = 'cliente') }}
                    {% elif session['tipo_usuario'] == 'master' %}
                        {{ url_for('master_bp.relatorio_pdf', tipo = 'cliente') }}
                    {% else %}
                        #
                    {% endif %}" target="_blank" class="btn btn-outline-primary w-100">
                    <i class="bi bi-file-earmark-pdf me-1 text-danger"></i> <strong>Gerar relatório</strong>
                </a>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped table-hover" id="tabelaUsuarios">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Gênero</th>
                        <th>Email</th>
                        <th>Telefone</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Excluir</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ cliente.nome }}</td>
                        <td>{{ cliente.genero }}</td>
                        <td>{{ cliente.email }}</td>
                        <td>{{ cliente.telefone }}</td>
                        <td class="text-center">
                            <button class="btn btn-sm btn-warning" data-bs-toggle="tooltip" data-bs-placement="left"
                                title="Editar cliente" data-bs-target="#editarModal{{ cliente.id }}"
                                onclick="new bootstrap.Modal(document.getElementById('editarModal{{ cliente.id }}')).show();">
                                <i class="fa fa-edit"></i>
                            </button>
                        </td>
                        <td class="text-center">
                            <button class="btn btn-sm btn-danger" data-bs-toggle="tooltip" data-bs-placement="left"
                                title="Excluir cliente" data-bs-target="#excluirModal{{ cliente.id }}"
                                onclick="new bootstrap.Modal(document.getElementById('excluirModal{{ cliente.id }}')).show();">
                                <i class="fa fa-trash"></i>
                            </button>

                        </td>
                    </tr>

                    <!-- Modal Editar -->
                    <div class="modal fade" id="editarModal{{ cliente.id }}" tabindex="-1"
                        aria-labelledby="editarModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form method="POST"
                                action="{{ url_for('master_bp.editar_usuario', id=cliente.id, tipo='cliente') }}">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Editar cliente</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <label><strong>Nome</strong></label>
                                        <input class="form-control" name="nome" value="{{ cliente.nome }}">
                                        <label class="mt-2"><strong>Email</strong></label>
                                        <input class="form-control" name="email" value="{{ cliente.email }}">
                                        <label class="mt-2"><strong>Telefone</strong></label>
                                        <input class="form-control" name="telefone" value="{{ cliente.telefone }}">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-success">Salvar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Modal Excluir -->
                    <div class="modal fade" id="excluirModal{{ cliente.id }}" tabindex="-1"
                        aria-labelledby="excluirModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form method="POST"
                                action="{{ url_for('master_bp.excluir_usuario', id=cliente.id, tipo='cliente') }}">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Confirmar Exclusão</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Tem certeza que deseja excluir <strong>{{ cliente.nome }}</strong>?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-danger">Sim, excluir</button>
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    

                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="footer">
            &copy; 2025. Todos os direitos reservados.
        </div>
    </main>
    <script src="{{ url_for('static', filename='main.js') }}"></script>

</body>

</html>

templates/cliente/relatorio_clientes.html
<!DOCTYPE html>
<html>

<head>
    <style>
        @page {
            size: A4 landscape;
            margin: 100px 50px 50px 50px;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
        }

        header {
            position: fixed;
            top: -80px;
            left: 0;
            right: 0;
            height: 60px;
            text-align: center;
            line-height: 35px;
            border-bottom: 1px solid #000;
        }

        .info {
            margin-bottom: 15px;
            font-weight: bold;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding-top: 4px;
            padding-left: 2px;
            vertical-align: middle; /* Centraliza verticalmente */
        }

        th {
            background: #eee;
        }

        tbody td {
            vertical-align: middle;
        }
    </style>
    <title>Relatório</title>
</head>

<body>

    <header>
        <h2>Relatório de Clientes - Sistema PetShop</h2>
    </header>

    <div class="info">
        <p>Emitido em: {{ current_date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 40px;">#</th>
                <th>Nome</th>
                {#<th>Gênero</th>#}
                <th>Email</th>
                <th>Telefone</th>
                <th>Endereço</th>
            </tr>
        </thead>
        <tbody>
            {% for u in cliente %}
            <tr>
                <td style="text-align: center; padding-left: 0;">{{ loop.index }}</td>
                <td>{{ u.nome }}</td>
                {#<td>{{ u.genero }}</td>#}
                <td>{{ u.email }}</td>
                <td>{{ u.telefone }}</td>
                <td>{{ u.rua }}, {{ u.numero }}, {{ u.bairro }}, {{ u.cidade }} - {{ u.estado }}, {{ u.cep }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>